version: 2.1
orbs:
  unity: gustomedialab/unity@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

pre-steps:
  mono: &mono
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the "mono" demo project
          git clone --branch master --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/gustomedialab/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD
  il2cpp: &il2cpp
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the "il2cpp" demo project
          git clone --branch windows-il2cpp --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/gustomedialab/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD
  custom-build-method: &custom-build-method
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the demo project with custom build method
          git clone --branch custom-build-method --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/gustomedialab/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD

workflows:
  test-build:
    jobs:
      # Activation file
      - unity/create-activation-file:
          name: "create-activation-file"
      - unity/create-activation-file:
          name: "create-activation-file-with-parameter"
          editor_version: 2022.1.11f1

      # Tests
      - unity/test:
          name: "test-linux"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.1f1"
            resource_class: "medium"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          test-platform: "playmode"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/test:
          name: "test-windows"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "windows-il2cpp"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          test-platform: "playmode"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/test:
          name: "test-osx"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/macos"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          test-platform: "playmode"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono

      # IL2CPP Builds
      - unity/build:
          name: "build-linux64-il2cpp"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneLinux64
          compress: true
          filters: *filters
          context: orb-testing-unity
          pre-steps: *il2cpp
      - unity/build:
          name: "build-Windows64-il2cpp"
          step-name: "Build StandaloneWindows64 il2cpp"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "windows-il2cpp"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneWindows64
          compress: true
          filters: *filters
          context: orb-testing-unity
          pre-steps: *il2cpp
      - unity/build:
          name: "build-osx-il2cpp"
          step-name: "Build macOS IL2CPP"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/macos"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneOSX
          compress: true
          filters: *filters
          context: orb-testing-unity
          pre-steps: *il2cpp

       # Mono Builds
      - unity/build:
          name: "build-linux64-mono"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "base"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneLinux64
          compress: true
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/build:
          name: "build-Windows64-mono"
          step-name: "Build StandaloneWindows64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "windows-mono"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: "StandaloneWindows64"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/build:
          name: "build-osx-mono"
          step-name: "Build StandaloneOSX"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "mac-mono"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: "StandaloneOSX"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono

      # Other Builds
      - unity/build:
          name: "build-webgl"
          step-name: "Build WebGL"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "webgl"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: "WebGL"
          compress: false
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/build:
          name: "build-android"
          step-name: "Build Android"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "android"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: "Android"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/build:
          name: "build-ios"
          step-name: "Build iOS"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "ios"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: "iOS"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/build:
          name: "build-tvOS"
          step-name: "Build Apple's tvOS"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "appletv"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: tvOS
          compress: true
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono

      # Other Tests
      - unity/build:
          name: "build-without-artifacts"
          step-name: "Build StandaloneLinux64 with no artifacts"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "base"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneLinux64
          store-artifacts: false
          filters: *filters
          context: orb-testing-unity
          pre-steps: *mono
      - unity/build:
          name: "build-with-custom-method-windows"
          step-name: "Build with custom method in Windows"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "windows-il2cpp"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneWindows64
          build-method: "MyCustomBuildCommand.MyCustomBuildMethod"
          custom-parameters: "-customParam1 potato -customParam2 tomato -customParam3 $CIRCLE_WORKFLOW_ID -DetailedBuildReport"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *custom-build-method
      - unity/build:
          name: "build-with-custom-method-osx"
          step-name: "Build with custom method in macOS"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/macos"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneOSX
          build-method: "MyCustomBuildCommand.MyCustomBuildMethod"
          custom-parameters: "-customParam1 potato -customParam2 tomato -customParam3 $CIRCLE_WORKFLOW_ID -DetailedBuildReport"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *custom-build-method
      - unity/build:
          name: "build-with-custom-method-linux"
          step-name: "Build with custom method in Linux"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneLinux64
          build-method: "MyCustomBuildCommand.MyCustomBuildMethod"
          custom-parameters: "-customParam1 potato -customParam2 tomato -customParam3 $CIRCLE_WORKFLOW_ID -DetailedBuildReport"
          compress: true
          filters: *filters
          context: orb-testing-unity
          pre-steps: *custom-build-method

      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: gustomedialab/unity
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - test-linux
            - test-windows
            - test-osx
            - build-linux64-il2cpp
            - build-Windows64-il2cpp
            - build-osx-il2cpp
            - build-linux64-mono
            - build-Windows64-mono
            - build-osx-mono
            - build-webgl
            - build-android
            - build-ios
            - build-tvOS
            - build-without-artifacts
            - build-with-custom-method-windows
            - build-with-custom-method-osx
            - build-with-custom-method-linux
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
